services:
  postgres:
    image: postgres:latest
    container_name: rentbik_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: phat1516
      POSTGRES_DB: rentbik
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build: .
    container_name: rentbik_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rentbik
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: phat1516
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: